apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv 
spec:
  storageClassName: mysql
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /mysql 
    server: 192.168.0.162 
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-backup-pv 
spec:
  storageClassName: mysql
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /mysql-backup 
    server: 192.168.0.162 
    readOnly: false
